import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import React from "react";
import type {Metadata, Viewport} from 'next'
import ClientRootLayout from '@/app/ClientRootLayout';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
}
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
        <ClientRootLayout>
            {children}
        </ClientRootLayout>
        </html>
    )
}
