import React from "react";
import type {Metadata} from 'next'
import Link from "next/link";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body style={{backgroundColor: '#666'}}>
        <Link href="/"><h2>Home</h2></Link>

        {children}</body>
        </html>
    )
}
